config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'
  # root 'searches#new'

  namespace :admin do
    resources :tickets, except: %i[new]
    resources :trains do
      resources :wagons
      # STI required
      resources :sitting_wagons, controller: 'wagons', type: 'SittingWagon'
      resources :economy_wagon, controller: 'wagons', type: 'EconomyWagon'
      resources :sleeping_wagon, controller: 'wagons', type: 'SleepingWagon'
      resources :coupe_wagons, controller: 'wagons', type: 'CoupeWagon'
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  resources :tickets

  # resolves search as singular resource
  resource :search, only: %i[new show]
  resolve('Search') { [:search] }
end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
  validate :stations_count

  has_many :railway_stations_routes, dependent: :destroy
  has_many :railway_stations, through: :railway_stations_routes, dependent: :destroy
  has_many :trains, dependent: :nullify

  after_save :set_indexes

  private

  def stations_count
    errors.add(:base, 'Route must contain at least 2 stations') if railway_stations.size < 2
  end

  def set_indexes
    # TODO: DO BULK UPDATE
    index = railway_stations.size.zero? ? railway_stations.size + 1 : 1
    railway_stations.each do |st|
      record = RailwayStationsRoute.find_by(railway_station: st, route: self)
      record.update(index_number: index) if record.index_number.nil?
      index += 1
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseAdminController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to admin_route_path(@route)
    else
      render new_admin_route_path, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_with model: [:admin, route], html: { id: "edit-form-#{route.id}", style: "display: #{hidden ? 'none' : 'block' }"} do |form| %>
  <% if route.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div id="optional-shown" style="display: <%= show_options ? 'block' : 'none'  %>">
    <div>
      <%= form.label :railway_station_ids, "Stations for route" %>
      <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true, selected: route.railway_station_ids } %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<div id="<%= dom_id route %>" style="border: 2px solid black; border-radius: 20px; margin: 10px auto; text-align: center" >
  <p>
    <strong>Title:</strong>
    <%= route.name %>
  </p>
  <%= render 'admin/routes/form', route: route, hidden: true, show_options: false %>
  <p><%= link_to "Edit", '', class: "edit_route_link", data: { route_id: route.id } %></p>
  <p><%= link_to "Show this route", admin_route_path(route) %></p>
</div>

app/views/admin/routes/edit.html.erb
<h1>Editing route</h1>

<%= render "form", route: @route, hidden: false, show_options: true %>

<br>

<div>
  <%= link_to "Show this route", [:admin, @route] %> |
  <%= link_to "Back to routes", admin_routes_path %>
</div>

app/views/admin/routes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Routes</h1>

<div id="routes">
    <%= render @routes %>
</div>

<%= link_to "New route", new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>New route</h1>

<%= render "form", route: @route, hidden: false, show_options: true %>

<br>

<div>
  <%= link_to "Back to routes", admin_routes_path %>
</div>

app/views/admin/routes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= @route.name %>
<% if @route.trains.empty? %>
  <%= 'No trains for this route'  %>
<% else %>
  <p><strong>Trains on route:</strong></p>
 <% @route.trains.each do |train| %>
  <%= train.number %>
  <% end %>
<% end %>

<p>Станции в маршруте</p>
<p>
  <% if @route.railway_stations.empty? %>
    No railway stations for this route
  <% else %>
    <table>
      <thead>
        <tr>
          <td style="width: 100px;">Name</td>
          <td>Index</td>
        </tr>
      </thead>
      <tbody>
        <% @route.railway_stations.ordered_by_index.each do |station| %>
          <tr>
            <td><%= station.title %></td>
            <td>
              <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
                <%= number_field_tag :index_number, station.index_number(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<div>
  <%= link_to "Edit this route", edit_admin_route_url(@route) %> |
  <%= link_to "Back to routes", admin_routes_path %>
  <%= button_to "Destroy this route", admin_route_url(@route), method: :delete %>
</div>