config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'
  # root 'searches#new'

  namespace :admin do
    resources :tickets, except: %i[new]
    resources :trains do
      resources :wagons
      # STI required
      resources :sitting_wagons, controller: 'wagons', type: 'SittingWagon'
      resources :economy_wagon, controller: 'wagons', type: 'EconomyWagon'
      resources :sleeping_wagon, controller: 'wagons', type: 'SleepingWagon'
      resources :coupe_wagons, controller: 'wagons', type: 'CoupeWagon'
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  resources :tickets

  # resolves search as singular resource
  resource :search, only: %i[new show]
  resolve('Search') { [:search] }
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-4">
    <p><%= link_to 'Список станций', admin_railway_stations_path %></p>
    <p><%= link_to 'Список поездов', admin_trains_path %></p>
    <p><%= link_to 'Список маршрутов', admin_routes_path %></p>
    <p><%= link_to 'Билеты', admin_tickets_path %></p>
    <p><%= link_to 'Поиск', new_search_path %></p>
  </div>
  <div class="col-md-8">
    <%= image_tag("dog.jpg", width: 300) %>
  </div>
</div>