config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'
  # root 'searches#new'

  namespace :admin do
    resources :tickets, except: %i[new]
    resources :trains do
      resources :wagons
      # STI required
      resources :sitting_wagons, controller: 'wagons', type: 'SittingWagon'
      resources :economy_wagon, controller: 'wagons', type: 'EconomyWagon'
      resources :sleeping_wagon, controller: 'wagons', type: 'SleepingWagon'
      resources :coupe_wagons, controller: 'wagons', type: 'CoupeWagon'
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  resources :tickets

  # resolves search as singular resource
  resource :search, only: %i[new show]
  resolve('Search') { [:search] }
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route

  has_many :tickets, dependent: :nullify
  has_many :wagons, dependent: :nullify

  def wagons_ordered
    if ordering == false
      wagons.order(index_number: :asc)
    else
      wagons.order(index_number: :desc)
    end
  end

  def count_places(wagons_type, places_type)
    wagons.where(type: wagons_type).sum(places_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseAdminController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  def create
    @train = Train.new(train_params)
    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Train was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Train was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :ordering)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_with model: [:admin, train], html: { id: "edit-form-#{train.id}", style: "display: #{hidden ? 'none' : 'block' }"} do |form| %>
  <%= render 'common/error', resource: train%>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div id="optional-shown" style="display: <%= show_options ? 'block' : 'none'  %>">
    <div class="field">
      <%= form.label :current_station %>
      <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
    </div>

    <div class="field">
      <%= form.label :route %>
      <%= form.collection_select :route_id, Route.all, :id, :name %>
    </div>

    <div class="field">
      <%= form.label :ordering %>
      <%= form.select :ordering, options_for_select([true, false], train.ordering || false ), class: 'form-control' %>
    </div>

    <div>
      <%= form.submit t('.submit', action: train.new_record? ? 'Создать' : 'Изменить') %>
    </div>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<div id="<%= dom_id train %>">
  <p>
    <div style='border: 3px solid black; padding: 5px'>
      <strong>Title:</strong>
      <div id='train-number-<%= train.id %>'>
        <%= train.number %>
      </div>
      <%= render 'admin/trains/form', train: train, hidden: true, show_options: false %>
      <%= link_to "Show", [:admin, train] %>
      <%= link_to "Edit", '', class: "edit_train_link", data: { train_id: train.id } %>
      <%= button_to "Destroy", [:admin, train], method: :delete %>
    </div>
  </p>
</div>

app/views/admin/trains/edit.html.erb
<h1>Editing train</h1>

<%= render "form", train: @train, hidden: false, show_options: true %>

<br>

<div>
  <%= link_to "Show this train", admin_train_path(@train) %> |
  <%= link_to "Back to trains", admin_trains_path %>
</div>

app/views/admin/trains/index.html.erb
<p style="color: green">

<h1>Trains</h1>

<div id="trains">
  <%= render @trains %>
</div>

<%= link_to "New train", new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", train: @train, hidden: false, show_options: true%>

<br>

<div>
  <%= link_to "Back to trains", admin_trains_path %>
</div>

app/views/admin/trains/show.html.erb
<p style="color: green"><%= notice %></p>

<strong>Train number: </strong><%= @train.number %> <br>
<%= @train.route.nil? ? 'Route isn\'t set for this train' : "Route: #{@train.route.name}"%> <br>

<p>Coupe wagons total: <%= @train.wagons.coupe_wagons.count %> </p>
<p>Economy wagons total: <%= @train.wagons.economy_wagons.count %> </p>
<p>Верхних купейных мест:<%= @train.count_places('CoupeWagon', 'top_seats') %> </p>
<p>Нижних купейных мест: <%= @train.count_places('CoupeWagon', 'bottom_seats') %> </p>
<p>Верхних плацкартных мест: <%= @train.count_places('EconomyWagon', 'top_seats') %> </p>
<p>Нижних плацкартных мест: <%= @train.count_places('EconomyWagon', 'bottom_seats')   %> </p>


<ul>
  <% @train.wagons_ordered.each do |wagon| %>
    <li>
      <p><%= link_to wagon.number, [:admin, @train, wagon] %></p>
    </li>
  <% end %>
</ul>
<%= link_to 'Add wagon', new_admin_train_wagon_path(@train)%>


<div style='margin-top: 10px;'>
  <%= link_to "Edit this train", edit_admin_train_path(@train) %>
  <%= link_to "Back to trains", admin_trains_path %>

  <%= button_to "Destroy this train", [:admin, @train], method: :delete %>
</div>