config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'
  # root 'searches#new'

  namespace :admin do
    resources :tickets, except: %i[new]
    resources :trains do
      resources :wagons
      # STI required
      resources :sitting_wagons, controller: 'wagons', type: 'SittingWagon'
      resources :economy_wagon, controller: 'wagons', type: 'EconomyWagon'
      resources :sleeping_wagon, controller: 'wagons', type: 'SleepingWagon'
      resources :coupe_wagons, controller: 'wagons', type: 'CoupeWagon'
    end

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :routes
    resources :tickets
  end

  resources :tickets

  # resolves search as singular resource
  resource :search, only: %i[new show]
  resolve('Search') { [:search] }
end

app/models/wagon.rb
class Wagon < ApplicationRecord
  # sets names to be displayed to user for each descendant of Wagon class
  WAGON_TYPES = { 'Wagon' => 'Abstract Wagon', 'CoupeWagon' => 'Coupe Wagon', 'EconomyWagon' => 'Economy Wagon',
                  'SittingWagon' => 'Sitting Wagon', 'SleepingWagon' => 'Sleeping Wagon' }.freeze

  belongs_to :train, optional: true

  validates :number, presence: true
  validates :number, uniqueness: true

  after_create :set_indexes

  scope :coupe_wagons, -> { where(type: 'CoupeWagon') }
  scope :economy_wagons, -> { where(type: 'EconomyWagon') }

  def self.wagon_types
    WAGON_TYPES
  end

  def self.wagon_types_for_selection
    WAGON_TYPES
  end

  private

  def set_indexes
    # TODO: DO BULK UPDATE
    index = train.wagons.size.zero? ? train.wagons.wagons.size + 1 : 1
    train.wagons.each do |wagon|
      wagon.update(index_number: index) if wagon.index_number.nil?
      index += 1
    end
  end
end

app/controllers/admin/wagons_controller.rb
class Admin::WagonsController < Admin::BaseAdminController
  before_action :set_wagon, only: %i[show edit update destroy]
  before_action :set_train, only: %i[destroy create new]

  # GET /wagons
  def index
    @wagons = Wagon.all
  end

  # GET /wagons/1
  def show; end

  # GET /wagons/new
  def new
    @wagon = Wagon.new
  end

  # GET /wagons/1/edit
  def edit; end

  # POST /wagons
  def create
    @wagon = @train.wagons.new(wagon_params)
    respond_to do |format|
      if @wagon.save
        format.html { redirect_to admin_train_path(@train), notice: 'Wagon was successfully updated.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wagons/1
  def update
    w_p = wagon_params
    @wagon = @wagon.becomes(w_p[:type].constantize)
    respond_to do |format|
      if @wagon.update(wagon_params)
        format.html { redirect_to admin_train_wagon_path(@wagon), notice: 'Wagon was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wagons/1
  def destroy
    @wagon.destroy

    respond_to do |format|
      format.html { redirect_to admin_train_path(@train), notice: 'Wagon was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or conswagonts between actions.
  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # Only allow a list of trusted parameters through.
  def wagon_params
    params.require(:wagon).permit(:number, :type, :top_seats, :bottom_seats, :side_top_seats,
                                        :side_bottom_seats, :train_id, :sitting_seats)
    # # changes type value form human-readable to rails-valid
    # w_p[:type] = Wagon.wagon_types.key(w_p[:type])
    # w_p
  end

  def set_train
    @train = Train.find(params[:train_id])
  end
end

app/views/admin/wagons/_form.html.erb
<style>
  .seats {
      display: none;
  }
</style>

<%= form_with(model: [:admin, wagon.becomes(Wagon)], url: url, method: method) do |form| %>
  <%= render 'common/error', resource: wagon%>
  <div>
    <%= form.label :number, 'Number', style: "display: block" %>
    <%= form.text_field :number, value: wagon.number %>
  </div>
  <div>
    <%= form.label :type, 'Type', style: "display: block" %>
    <%= form.select :type, options_for_select(Wagon.wagon_types.invert, wagon.type), id: 'wagon-type-chooser' %>
  </div>
  <div id="top_seats" class="seats">
    <%= form.label :top_seats, 'Amount of top places', style: "display: block" %>
    <%= form.number_field :top_seats, :min => 0 %>
  </div>
  <div id="bottom_seats" class="seats">
    <%= form.label :bottom_seats, 'Amount of lower places', style: "display: block" %>
    <%= form.number_field :bottom_seats, :min => 0 %>
  </div>
  <div id="side_top_seats" class="seats">
    <%= form.label :side_top_seats, 'Amount of side top places', style: "display: block" %>
    <%= form.number_field :side_top_seats, :min => 0 %>
  </div>
  <div id="side_bottom_seats" class="seats">
    <%= form.label :side_bottom_seats, 'Amount of side lower places', style: "display: block" %>
    <%= form.number_field :side_bottom_seats, :min => 0 %>
  </div>
  <div id="sitting_seats" class="seats">
    <%= form.label :sitting_seats, 'Amount of sitting places', style: "display: block" %>
    <%= form.number_field :sitting_seats, :min => 0 %>
  </div>
  <div class="field" class="seats">
    <%= form.label :train, 'Train' %>
    <%= form.collection_select :train_id, Train.all, :id, :number %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/wagons/edit.html.erb
<h1>Editing wagon</h1>

<%= render "form", wagon: @wagon, url: admin_train_wagon_path(@wagon.train, @wagon), method: :patch %>

app/views/admin/wagons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wagons</h1>

<div id="wagons">
  <%= render partial: "wagon", collection: @wagons, as: :wagon %>
</div>

<%= link_to "New wagon", new_admin_train_path %>

app/views/admin/wagons/new.html.erb
<h1>New wagon</h1>

<%= render "form", wagon: @wagon, url: admin_train_wagons_path(@train), method: :post %>

app/views/admin/wagons/show.html.erb
<p style="color: green"><%= notice %></p>

<strong>Wagon number: </strong><%= @wagon.number %> <br>
<p>Wagon type: <%= @wagon.type || 'Base wagon' %></p>
<p>Top seats: <%= @wagon.top_seats || 0 %></p>
<p>Bottom seats: <%= @wagon.bottom_seats || 0 %></p>
<% if @wagon.type == 'EconomyWagon' %>
  <p>Side top seats: <%= @wagon.side_top_seats %></p>
  <p>Side bottom seats: <%= @wagon.side_bottom_seats %></p>
<% elsif @wagon.type == 'SittingWagon' %>
  <p>Sitting seats: <%= @wagon.sitting_seats %></p>
<%end %>
<div style='margin-top: 10px;'>
  <%= link_to "Edit this wagon", edit_admin_train_wagon_path(@wagon.train), url: admin_train_wagons_path, method: :get %> |
  <%= button_to "Destroy this wagon", admin_train_wagon_path, url: admin_train_wagon_path, method: :delete %>
</div>
<div>
  <%= link_to "Back", admin_train_path(@wagon.train) %>
</div>